image: docker:latest

services:
  - docker:dind

before_script:
  - echo $GOOGLE_MAPS_ANDROID_API_KEY
  - cat mobile/config.xml
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

stages:
  - build

build_debug:
  stage: build
  script:
    - cd mobile
    - docker-compose up -d --build
    - docker exec mobile_app_1 npm run build-clean:android:prod
    - if ! [[ -e platforms/android/app/build/outputs/apk/debug/app-debug.apk ]]; then exit 1; fi
  only:
    - gitlab-ci
  artifacts:
    paths:
      - mobile/platforms/android/app/build/outputs/apk/debug/app-debug.apk