image: docker:latest

services:
  - docker:dind

before_script:
  - cp mobile/.env-sample mobile/.env
  - while read a ; do echo ${a//%GOOGLE_MAPS_ANDROID_API_KEY%/$GOOGLE_MAPS_ANDROID_API_KEY} ; done < mobile/.env > mobile/.env.t ; mv mobile/.env.t mobile/.env
  - cat mobile/.env
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

stages:
  - build

build_debug:
  stage: build
  script:
    - cd mobile
    - docker-compose up -d --build
    - docker exec mobile_app_1 npm run build-clean:android:prod
    - if ! [[ -e platforms/android/app/build/outputs/apk/debug/app-debug.apk ]]; then exit 1; fi
  artifacts:
    paths:
      - mobile/platforms/android/app/build/outputs/apk/debug/app-debug.apk