# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

build:
  stage: build
  script:
    - cd mobile
    - docker-compose up -d --build
    - docker exec mobile_app_1 npm run build-clean:android:prod
  only:
    - gitlab-ci