languages:
  JavaScript: true
  Typescript: true

exclude_patterns:
  - config/**/*
  - node_modules/**/*
  - webpack.*.js
  - karma.conf.js
  - platforms/
  - plugins/
  - '**/*.spec.ts'

plugins:
  tslint:
    enabled: true
    config: tslint.json

version: '2'
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
