languages:
  JavaScript: true
  Typescript: true

exclude_patterns:
  - config/**/*
  - node_modules/**/*
  - e2e/
  - webpack.*.js
  - karma.conf.js
  - image-files/
  - platforms/
  - plugins/
  - www/
  - '**/*.spec.ts'
  - '**/*.conf.js'
version: '2'
