version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdsteam/sapawarga_mobile:1.0
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - /app/node_modules