version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-ionic/sapawarga-ionic:${VERSION}
    env_file:
      - .env
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - /app/node_modules